### ISSUE TITLE
Trying to build the theme for Pale Moon 27.3.0

### ISSUE THREAD

**Issue by rustydroid** [Fred-Barclay/arc-palemoon-theme#1]
@Fred-Barclay 
not sure if you still are the maintainer of this repo, but I'm trying to  build this theme for last Pale moon version, 27.3.0, but I was not able to do it.
I don't have too much knowledge on this kind of addons, but I tried to modify install.rdf file to match the version, without luck.
Hope you can give me a hand on this.
Many thanks in advance.

**Comment by Fred-Barclay** [comment]
Hi @godzeus 
Sorry, but I haven't worked with this in quite some time! 😄 I do recall that I had to change the UID in install.rdf, but I don't remember what needed to be changed. [This](https://github.com/Lootyhoof/darkmoon/blob/master/src/install.rdf) might be a good place to start and see what install.rdf should look like.

Cheers!
Fred
